### ISSUE TITLE
More lines on README

### ISSUE THREAD

**Issue by Heavenboi** [DestinedCodes/simple_shell#2]
I have added new lines on the readme file, Check it out.

**Comment by sshdopey** [comment]
This issue didn't need to be created. You'd had instead written this in the #1 PR as a comment. 

I'll leave you to close this yourself and go drop a comment in the #1 PR saying that you've fixed the issue.


We would need to use issue when we see a big bug or needed feature to be implemented since there is a PR open in this course all conversation should be there. 


Close this issue yourself and explain the changes you made in the earlier created Pull Request. PR means Pull Request

**Comment by Heavenboi** [comment]
Issue closed.
